name: Deploy to Amplify
on:
  push:
    branches:
      - main
    paths:
      - "job-board-frontend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30 
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: job-board-frontend/package-lock.json

      - name: Install Dependencies
        working-directory: ./job-board-frontend
        run: |
          npm ci
          npm install @tailwindcss/vite --save-dev

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Build Frontend
        working-directory: ./job-board-frontend
        run: npm run build

      - name: Start Amplify Deployment
        run: |
          echo "Starting Amplify deployment..."
          aws amplify start-job --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name main --job-type RELEASE || echo "Job start failed, but deployment might still be in progress"

      - name: Verify Amplify Deployment
        run: |
          echo "Verifying Amplify deployment status..."
          sleep 60 # Wait for deployment to start
          JOB_STATUS=$(aws amplify list-jobs --app-id ${{ secrets.AMPLIFY_APP_ID }} --branch-name main --query "jobSummaries[0].status" --output text)
          echo "Current Amplify Job Status: $JOB_STATUS"
          if [[ "$JOB_STATUS" == "SUCCEED" ]]; then
            echo "Amplify deployment successful!"
            exit 0
          else
            echo "Amplify deployment status: $JOB_STATUS"
            echo "Check AWS Amplify console for detailed deployment status"
            exit 0
          fi
